[project]
name = "markutils"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "pandas",
    "pyarrow",
    "safetensors",
]

[project.scripts]
markutils = "markutils:cli.main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "ipython",
    "pytest",
    "ruff",
]

[tool.pytest.ini_options]
pythonpath = ["src"]
